# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
GP1_pmf_scalar <- function(mu, phi, Y) {
    .Call(`_GMVJM_GP1_pmf_scalar`, mu, phi, Y)
}

#' @keywords internal
ll_genpois <- function(eta, phi, Y) {
    .Call(`_GMVJM_ll_genpois`, eta, phi, Y)
}

#' @keywords internal
logfti <- function(b, S, SS, Fi, Fu, l0i, haz, Delta, gamma_rep, zeta) {
    .Call(`_GMVJM_logfti`, b, S, SS, Fi, Fu, l0i, haz, Delta, gamma_rep, zeta)
}

#' @keywords internal
joint_density <- function(b, Y, X, Z, beta, D, sigma, family, Delta, S, Fi, l0i, SS, Fu, haz, gamma_rep, zeta, beta_inds, b_inds, K) {
    .Call(`_GMVJM_joint_density`, b, Y, X, Z, beta, D, sigma, family, Delta, S, Fi, l0i, SS, Fu, haz, gamma_rep, zeta, beta_inds, b_inds, K)
}

#' @keywords internal
Score_eta_poiss_quad <- function(eta, Y, tau2, w, v) {
    .Call(`_GMVJM_Score_eta_poiss_quad`, eta, Y, tau2, w, v)
}

#' @keywords internal
joint_density_ddb <- function(b, Y, X, Z, beta, D, sigma, family, Delta, S, Fi, l0i, SS, Fu, haz, gamma_rep, zeta, beta_inds, b_inds, K) {
    .Call(`_GMVJM_joint_density_ddb`, b, Y, X, Z, beta, D, sigma, family, Delta, S, Fi, l0i, SS, Fu, haz, gamma_rep, zeta, beta_inds, b_inds, K)
}

#' @keywords internal
Sbeta <- function(beta, X, Y, Z, b, sigma, family, beta_inds, K) {
    .Call(`_GMVJM_Sbeta`, beta, X, Y, Z, b, sigma, family, beta_inds, K)
}

#' @keywords internal
Hess_eta_poiss_quad <- function(eta, Y, design, tau2, w, v) {
    .Call(`_GMVJM_Hess_eta_poiss_quad`, eta, Y, design, tau2, w, v)
}

#' @keywords internal
Hess_eta_genpois <- function(eta, Y, phi, design) {
    .Call(`_GMVJM_Hess_eta_genpois`, eta, Y, phi, design)
}

#' @keywords internal
Hbeta <- function(beta, X, Y, Z, b, sigma, family, beta_inds, K) {
    .Call(`_GMVJM_Hbeta`, beta, X, Y, Z, b, sigma, family, beta_inds, K)
}

#' @keywords internal
vare_update <- function(X, Y, Z, b, beta, tau, w, v) {
    .Call(`_GMVJM_vare_update`, X, Y, Z, b, beta, tau, w, v)
}

#' @keywords internal
phi_update <- function(b, X, Y, Z, beta, phi, w, v, tau) {
    .Call(`_GMVJM_phi_update`, b, X, Y, Z, beta, phi, w, v, tau)
}

#' @keywords internal
Sgammazeta <- function(gammazeta, b, Sigma, S, SS, Fu, Fi, haz, Delta, w, v, b_inds, K, q, eps) {
    .Call(`_GMVJM_Sgammazeta`, gammazeta, b, Sigma, S, SS, Fu, Fi, haz, Delta, w, v, b_inds, K, q, eps)
}

#' @keywords internal
Hgammazeta <- function(gammazeta, b, Sigma, S, SS, Fu, Fi, haz, Delta, w, v, b_inds, K, q, eps) {
    .Call(`_GMVJM_Hgammazeta`, gammazeta, b, Sigma, S, SS, Fu, Fi, haz, Delta, w, v, b_inds, K, q, eps)
}

#' @keywords internal
lambdaUpdate <- function(survtimes, ft, gamma, gamma_rep, zeta, S, Sigma, b, w, v, b_inds, K, q) {
    .Call(`_GMVJM_lambdaUpdate`, survtimes, ft, gamma, gamma_rep, zeta, S, Sigma, b, w, v, b_inds, K, q)
}

#' @keywords internal
joint_density_sdb <- function(b, Y, X, Z, beta, D, sigma, family, Delta, S, Fi, l0i, SS, Fu, haz, gamma_rep, zeta, beta_inds, b_inds, K, eps) {
    .Call(`_GMVJM_joint_density_sdb`, b, Y, X, Z, beta, D, sigma, family, Delta, S, Fi, l0i, SS, Fu, haz, gamma_rep, zeta, beta_inds, b_inds, K, eps)
}

